version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${DOCKER_PORT}"
    environment:
      - DATABASE_URL=${DB_URL}
    depends_on:
      - db
    networks: 
      - blog

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - blog

volumes:
  postgres_data:

networks:
  blog: {}
